apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-experimental

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-experimental-template-controller
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: tekton-experimental-template-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-experimental

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-experimental-template-controller-cluster-access
  labels:
    app.kubernetes.io/component: tekton-experimental-template-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-experimental
rules:
  # Controller needs cluster access to all Run CRs.
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns/finalizers"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns/status"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

  # Controller needs permission to configure master-election.
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

  # Controller needs permission to emit events associated with Run CRs.
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-experimental-template-controller
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: tekton-experimental-template-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-experimental
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "watch"]
  # The controller needs access to these configmaps for logging information and runtime configuration.
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
    resourceNames: ["config-logging", "config-observability", "config-leader-election"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-experimental-template-controller
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: tekton-experimental-template-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-experimental
subjects:
  - kind: ServiceAccount
    name: tekton-experimental-template-controller
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-experimental-template-controller
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-experimental-template-controller-cluster-access
  labels:
    app.kubernetes.io/component: tekton-experimental-template-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-experimental
subjects:
  - kind: ServiceAccount
    name: tekton-experimental-template-controller
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-experimental-template-controller-cluster-access
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-experimental
data:
  # Common configuration for all knative codebase
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }

  # Log level overrides
  loglevel.controller: "info"
  loglevel.webhook: "info"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-experimental-template-controller
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: tekton-experimental-template-controller
    app.kubernetes.io/component: tekton-experimental-template-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: tekton-experimental
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-experimental-template-controller
      app.kubernetes.io/component: tekton-experimental-template-controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-experimental
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/name: tekton-experimental-template-controller
        app.kubernetes.io/component: tekton-experimental-template-controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: devel
        app.kubernetes.io/part-of: tekton-experimental
        app: tekton-experimental-template-controller
    spec:
      serviceAccountName: tekton-experimental-template-controller
      containers:
      - name: tekton-experimental-template-controller
        image: ko://github.com/tektoncd/experimental/tekton-experimental-template/cmd/controller
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # If you are changing these names, you will also need to update
        # the controller's Role in 200-role.yaml to include the new
        # values in the "configmaps" "get" rule.
        - name: CONFIG_LOGGING_NAME
          value: config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tekton-experimental-template-controller
    app.kubernetes.io/component: tekton-experimental-template-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: tekton-experimental
    # tekton.dev/release value replaced with inputs.params.versionTag in pipeline/tekton/publish.yaml
    pipeline.tekton.dev/release: "devel"
    # labels below are related to istio and should not be used for resource lookup
    app: tekton-experimental-template-controller
    version: "devel"
  name: tekton-experimental-template-controller
  namespace: tekton-pipelines
spec:
  ports:
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: tekton-experimental-template-controller
    app.kubernetes.io/component: tekton-experimental-template-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-experimental
